# Generated by Django 3.2.9 on 2021-11-29 08:59

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_auto_20211125_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRepository',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
        ),
    ]
