# Generated by Django 3.2.9 on 2021-11-24 12:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(blank=True, max_length=50, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('password', models.CharField(blank=True, max_length=100, verbose_name='Пароль')),
                ('active', models.BooleanField(blank=True, max_length=1, verbose_name='Активность')),
                ('status', models.BooleanField(blank=True, max_length=1, verbose_name='Сложная авторизация')),
                ('last_visit', models.DateTimeField(blank=True, verbose_name='Дата последнего визита')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['fio'],
            },
        ),
        migrations.CreateModel(
            name='UserExtSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('man', 'Man'), ('woman', 'Woman')], default='MAN', max_length=5)),
                ('age', models.IntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(1)], verbose_name='Возраст')),
                ('height', models.FloatField(blank=True, max_length=300, verbose_name='Рост')),
                ('weight', models.FloatField(blank=True, max_length=200, verbose_name='Вес')),
                ('neck', models.FloatField(blank=True, max_length=100, verbose_name='Шея')),
                ('shoulders', models.FloatField(blank=True, max_length=200, verbose_name='Плечи')),
                ('chest_relax', models.FloatField(blank=True, max_length=200, verbose_name='Грудь расслабленная')),
                ('chest_tense', models.FloatField(blank=True, max_length=200, verbose_name='Грудь напряженная')),
                ('left_biceps_relax', models.FloatField(blank=True, max_length=100, verbose_name='Левый бицепс расслабленный')),
                ('right_biceps_relax', models.FloatField(blank=True, max_length=100, verbose_name='Правый бицепс расслабленный')),
                ('left_biceps_tense', models.FloatField(blank=True, max_length=100, verbose_name='Левый бицепс напряженный')),
                ('right_biceps_tense', models.FloatField(blank=True, max_length=100, verbose_name='Правый бицепс напряженный')),
                ('left_forearm', models.FloatField(blank=True, max_length=100, verbose_name='Левое предплечье')),
                ('right_forearm', models.FloatField(blank=True, max_length=100, verbose_name='Правое предплечье')),
                ('pelvis', models.FloatField(blank=True, max_length=200, verbose_name='Таз')),
                ('waist', models.FloatField(blank=True, max_length=200, verbose_name='Талия')),
                ('left_thigh', models.FloatField(blank=True, max_length=100, verbose_name='Бедро левое')),
                ('right_thigh', models.FloatField(blank=True, max_length=100, verbose_name='Бедро правое')),
                ('left_shin', models.FloatField(blank=True, max_length=100, verbose_name='Голень левая')),
                ('right_shin', models.FloatField(blank=True, max_length=100, verbose_name='Голень правая')),
                ('body_mass_index', models.FloatField(blank=True, max_length=100, verbose_name='Индекс массы тела')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'verbose_name': 'Дополнительная настройка',
                'verbose_name_plural': 'Дополнительные настройки',
                'ordering': ['user'],
            },
        ),
    ]
