# Generated by Django 3.2.9 on 2021-11-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211125_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextsettings',
            name='gender',
            field=models.CharField(choices=[('man', 'Мужчина'), ('woman', 'Женщина')], default='MAN', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='userextsettings',
            name='height',
            field=models.FloatField(blank=True, max_length=300, null=True, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='userextsettings',
            name='weight',
            field=models.FloatField(blank=True, max_length=200, null=True, verbose_name='Вес'),
        ),
    ]
