# Generated by Django 3.2.9 on 2021-11-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211125_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextsettings',
            name='body_mass_index',
            field=models.FloatField(max_length=100, null=True, verbose_name='Индекс массы тела'),
        ),
        migrations.AlterField(
            model_name='userextsettings',
            name='chest_relax',
            field=models.FloatField(max_length=200, null=True, verbose_name='Грудь расслабленная'),
        ),
        migrations.AlterField(
            model_name='userextsettings',
            name='chest_tense',
            field=models.FloatField(max_length=200, null=True, verbose_name='Грудь напряженная'),
        ),
        migrations.AlterField(
            model_name='userextsettings',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='userextsettings',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='userextsettings',
            name='left_biceps_relax',
            field=models.FloatField(max_length=100, null=True, verbose_name='Левый бицепс расслабленный'),
        ),
        migrations.AlterField(
            model_name='userextsettings',
            name='left_biceps_tense',
            field=models.FloatField(max_length=100, null=True, verbose_name='Левый бицепс напряженный'),
        ),
        migrations.AlterField(
            model_name='userextsettings',
            name='left_forearm',
            field=models.FloatField(max_length=100, null=True, verbose_name='Левое предплечье'),
        ),
        migrations.AlterField(
            model_name='userextsettings',
            name='left_shin',
            field=models.FloatField(max_length=100, null=True, verbose_name='Голень левая'),
        ),
        migrations.AlterField(
            model_name='userextsettings',
            name='left_thigh',
            field=models.FloatField(max_length=100, null=True, verbose_name='Бедро левое'),
        ),
        migrations.AlterField(
            model_name='userextsettings',
            name='neck',
            field=models.FloatField(max_length=100, null=True, verbose_name='Шея'),
        ),
        migrations.AlterField(
            model_name='userextsettings',
            name='pelvis',
            field=models.FloatField(max_length=200, null=True, verbose_name='Таз'),
        ),
        migrations.AlterField(
            model_name='userextsettings',
            name='right_biceps_relax',
            field=models.FloatField(max_length=100, null=True, verbose_name='Правый бицепс расслабленный'),
        ),
        migrations.AlterField(
            model_name='userextsettings',
            name='right_biceps_tense',
            field=models.FloatField(max_length=100, null=True, verbose_name='Правый бицепс напряженный'),
        ),
        migrations.AlterField(
            model_name='userextsettings',
            name='right_forearm',
            field=models.FloatField(max_length=100, null=True, verbose_name='Правое предплечье'),
        ),
        migrations.AlterField(
            model_name='userextsettings',
            name='right_shin',
            field=models.FloatField(max_length=100, null=True, verbose_name='Голень правая'),
        ),
        migrations.AlterField(
            model_name='userextsettings',
            name='right_thigh',
            field=models.FloatField(max_length=100, null=True, verbose_name='Бедро правое'),
        ),
        migrations.AlterField(
            model_name='userextsettings',
            name='shoulders',
            field=models.FloatField(max_length=200, null=True, verbose_name='Плечи'),
        ),
        migrations.AlterField(
            model_name='userextsettings',
            name='waist',
            field=models.FloatField(max_length=200, null=True, verbose_name='Талия'),
        ),
    ]
