# Generated by Django 3.2.9 on 2021-11-25 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211125_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextsettings',
            name='height',
            field=models.FloatField(blank=True, max_length=300, null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(1)], verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='userextsettings',
            name='weight',
            field=models.FloatField(blank=True, max_length=200, null=True, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(1)], verbose_name='Вес'),
        ),
    ]
