# Generated by Django 3.2.9 on 2021-11-29 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211125_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalBodyParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(blank=True, max_length=300, null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(1)], verbose_name='Рост')),
                ('weight', models.FloatField(blank=True, max_length=200, null=True, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(1)], verbose_name='Вес')),
                ('neck', models.FloatField(max_length=100, null=True, verbose_name='Шея')),
                ('shoulders', models.FloatField(max_length=200, null=True, verbose_name='Плечи')),
                ('chest_relax', models.FloatField(max_length=200, null=True, verbose_name='Грудь расслабленная')),
                ('waist', models.FloatField(max_length=200, null=True, verbose_name='Талия')),
                ('left_thigh', models.FloatField(max_length=100, null=True, verbose_name='Бедро левое')),
                ('right_thigh', models.FloatField(max_length=100, null=True, verbose_name='Бедро правое')),
                ('left_shin', models.FloatField(max_length=100, null=True, verbose_name='Голень левая')),
                ('right_shin', models.FloatField(max_length=100, null=True, verbose_name='Голень правая')),
            ],
            options={
                'verbose_name': 'Нормальный параметр тела',
                'verbose_name_plural': 'Нормальные параметры тела',
                'db_table': 'normal_body_param',
            },
        ),
    ]
