# Generated by Django 3.2.9 on 2021-11-29 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_usergoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalbodyparam',
            name='goal',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='core.goals'),
        ),
    ]
