# Generated by Django 3.2.9 on 2021-11-29 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_normalbodyparam_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.URLField(verbose_name='Картинка')),
                ('category', models.CharField(max_length=250)),
                ('main_muscles', models.TextField(verbose_name='Основные мышцы')),
                ('minor_muscles', models.TextField(verbose_name='Второстепенные мышцы')),
                ('sport_equipment', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='normalbodyparam',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.goals'),
        ),
        migrations.CreateModel(
            name='BodyWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('date_created', models.DateTimeField()),
                ('date_finish', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('publications', models.ManyToManyField(to='core.BodyExercise')),
            ],
        ),
    ]
