# Generated by Django 3.2.9 on 2021-11-29 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_bodyworkout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyworkout',
            name='date_finish',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bodyworkout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
    ]
