# Generated by Django 3.2.9 on 2021-11-29 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20211129_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyworkout',
            name='goal',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.goals'),
        ),
    ]
