# Generated by Django 3.2.9 on 2021-11-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20211129_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('cal', models.IntegerField(verbose_name='Количество каллорий')),
            ],
        ),
    ]
