# Generated by Django 3.2.9 on 2021-11-25 08:55

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_auto_20211125_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
        ),
    ]
